# Generated by Django 3.2.9 on 2022-06-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=2),
        ),
    ]
