from .utils import *
from book.views.rental import *
from .crud_view import *
from book.views.template_views.mypage import *
from book.views.template_views.mainpage_templates_view import *
from book.views.template_views.categorys_templates_view import *
from .template_views.mybook_template_view import *
from .template_views.rental_edit_template_view import *
from .template_views.rental_new_template_view import *
from .template_views.book_list_template_view import *
from .template_views.myborrowed_book_template_view import *